import type { ATM, Technician, MaintenanceTask, Employee, Bank, BankContract, ATMData, WorkPlan, Governorate, City, WorkPlanReport, Note } from './types';
import { subDays, addDays } from 'date-fns';

export const atms: ATM[] = [
  {
    id: 'atm-001',
    location: '123 Main St, Metropolis',
    bank: 'Metro Bank',
    status: 'Active',
    lastMaintenanceDate: subDays(new Date(), 30).toISOString(),
    maintenancePlan: 'Quarterly',
  },
  {
    id: 'atm-002',
    location: '456 Oak Ave, Gotham',
    bank: 'Gotham Trust',
    status: 'Maintenance',
    lastMaintenanceDate: subDays(new Date(), 10).toISOString(),
    maintenancePlan: 'Biannually',
  },
  {
    id: 'atm-003',
    location: '789 Pine Ln, Star City',
    bank: 'Starling National',
    status: 'Active',
    lastMaintenanceDate: subDays(new Date(), 90).toISOString(),
    maintenancePlan: 'Quarterly',
  },
  {
    id: 'atm-004',
    location: '101 Maple Dr, Central City',
    bank: 'Flash Financial',
    status: 'Inactive',
    lastMaintenanceDate: subDays(new Date(), 200).toISOString(),
    maintenancePlan: 'Annually',
  },
  {
    id: 'atm-005',
    location: '212 Birch Rd, Coast City',
    bank: 'Lantern Credit Union',
    status: 'Active',
    lastMaintenanceDate: subDays(new Date(), 60).toISOString(),
    maintenancePlan: 'Biannually',
  },
];

export const technicians: Technician[] = [
  {
    id: 'tech-01',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '555-1234',
    avatarId: 'avatar1',
    tasksCompleted: 25,
    avgResolutionTime: 4.5,
  },
  {
    id: 'tech-02',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-5678',
    avatarId: 'avatar2',
    tasksCompleted: 30,
    avgResolutionTime: 3.8,
  },
  {
    id: 'tech-03',
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    phone: '555-8765',
    avatarId: 'avatar3',
    tasksCompleted: 18,
    avgResolutionTime: 5.1,
  },
  {
    id: 'tech-04',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '555-4321',
    avatarId: 'avatar4',
    tasksCompleted: 42,
    avgResolutionTime: 3.2,
  },
];

export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: 'task-001',
    atmId: 'atm-002',
    technicianId: 'tech-02',
    description: 'Replace card reader',
    scheduledDate: new Date().toISOString(),
    status: 'In Progress',
    priority: 'High',
  },
  {
    id: 'task-002',
    atmId: 'atm-003',
    technicianId: 'tech-01',
    description: 'Routine software update',
    scheduledDate: addDays(new Date(), 5).toISOString(),
    status: 'Pending',
    priority: 'Medium',
  },
  {
    id: 'task-003',
    atmId: 'atm-001',
    technicianId: 'tech-04',
    description: 'Cash dispenser calibration',
    scheduledDate: subDays(new Date(), 2).toISOString(),
    status: 'Completed',
    priority: 'Medium',
  },
  {
    id: 'task-004',
    atmId: 'atm-004',
    technicianId: null,
    description: 'Full system diagnostic',
    scheduledDate: addDays(new Date(), 10).toISOString(),
    status: 'Pending',
    priority: 'Low',
  },
  {
    id: 'task-005',
    atmId: 'atm-005',
    technicianId: 'tech-02',
    description: 'Receipt printer jam',
    scheduledDate: subDays(new Date(), 7).toISOString(),
    status: 'Completed',
    priority: 'High',
  },
    {
    id: 'task-006',
    atmId: 'atm-001',
    technicianId: 'tech-03',
    description: 'Quarterly security check',
    scheduledDate: addDays(new Date(), 15).toISOString(),
    status: 'Pending',
    priority: 'Medium',
  },
];


export const employees: Employee[] = [
    {
        id: 'emp-001',
        nameAr: 'نور',
        nameEn: 'Noor',
        city: 'الرياض',
        hireDate: subDays(new Date(), 45).toISOString(),
        mobile: '555-1111',
        avatarId: 'avatar2',
    },
    {
        id: 'emp-002',
        nameAr: 'علي',
        nameEn: 'Ali',
        city: 'جدة',
        hireDate: subDays(new Date(), 120).toISOString(),
        mobile: '555-2222',
        avatarId: 'avatar1',
    },
    {
        id: 'emp-003',
        nameAr: 'فاطمة',
        nameEn: 'Fatima',
        city: 'الدمام',
        hireDate: subDays(new Date(), 300).toISOString(),
        mobile: '555-3333',
        avatarId: 'avatar4',
    },
];

export const banks: Bank[] = [
    {
        id: 'bank-001',
        nameAr: 'بنك الإسكندرية',
        nameEn: 'Bank of Alexandria',
        governorate: 'الإسكندرية',
        city: 'الإسكندرية',
        address: '1 شارع فؤاد، الإسكندرية',
        mobile: '19033',
        logoId: 'avatar1',
    },
    {
        id: 'bank-002',
        nameAr: 'البنك العربي الإفريقي الدولي',
        nameEn: 'Arab African International Bank',
        governorate: 'القاهرة',
        city: 'القاهرة الجديدة',
        address: '2 شارع التسعين الجنوبي، التجمع الخامس',
        mobile: '19555',
        logoId: 'avatar2',
    },
    {
        id: 'bank-003',
        nameAr: 'بنك الإمارات دبي الوطني',
        nameEn: 'Emirates NBD Egypt',
        governorate: 'الجيزة',
        city: 'الشيخ زايد',
        address: 'مول العرب، ميدان جهينة',
        mobile: '16664',
        logoId: 'avatar3',
    }
];

export const bankContracts: BankContract[] = [
    {
        id: 'contract-001',
        bankName: 'بنك الإسكندرية',
        startDate: subDays(new Date(), 365).toISOString(),
        endDate: addDays(new Date(), 365).toISOString(),
        machineNumber: 'MC-12345',
        contractValue: 50000,
        statement: 'عقد صيانة سنوي',
        fileUrl: '#'
    },
    {
        id: 'contract-002',
        bankName: 'البنك العربي الإفريقي الدولي',
        startDate: subDays(new Date(), 180).toISOString(),
        endDate: addDays(new Date(), 185).toISOString(),
        machineNumber: 'MC-67890',
        contractValue: 75000,
        statement: 'عقد توريد وتركيب',
        fileUrl: '#'
    },
];

export const atmData: ATMData[] = [
    { id: "atm-data-151", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Heliopolis Branch", atmSerial: "Heliopolis", atmCode: "EGBN001", atmAddress: "43 شارع الحرية، هليوبوليس" },
    { id: "atm-data-152", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Heliopolis Club", atmSerial: "Heliopolis", atmCode: "EGBW001", atmAddress: "نادي هليوبوليس الرياضي" },
    { id: "atm-data-153", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Korba", atmSerial: "Heliopolis", atmCode: "EGBW020", atmAddress: "15 شارع بغداد، الكوربة" },
    { id: "atm-data-154", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Merghany", atmSerial: "Heliopolis", atmCode: "EGBW040", atmAddress: "78 شارع الميرغني" },
    { id: "atm-data-155", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "City Stars Mall", atmSerial: "Heliopolis", atmCode: "EGBW060", atmAddress: "سيتي ستارز مول، المرحلة الاولى" },
    { id: "atm-data-156", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Sun City Mall", atmSerial: "Heliopolis", atmCode: "EGBW080", atmAddress: "صن سيتي مول" },
    { id: "atm-data-157", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Tivoli Dome", atmSerial: "Heliopolis", atmCode: "EGBW100", atmAddress: "تيفولي دوم" },
    { id: "atm-data-158", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "Abbas El Akkad Branch", atmSerial: "Nasr City", atmCode: "EGBN002", atmAddress: "32 شارع عباس العقاد" },
    { id: "atm-data-159", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "Makram Ebeid", atmSerial: "Nasr City", atmCode: "EGBW002", atmAddress: "41 شارع مكرم عبيد" },
    { id: "atm-data-160", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "Genena Mall", atmSerial: "Nasr City", atmCode: "EGBW021", atmAddress: "جنينة مول" },
    { id: "atm-data-161", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "City Center Almaza", atmSerial: "Nasr City", atmCode: "EGBW041", atmAddress: "سيتي سنتر ألماظة" },
    { id: "atm-data-162", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "New Cairo Branch", atmSerial: "New Cairo", atmCode: "EGBN003", atmAddress: "القطاع الأول، مركز المدينة" },
    { id: "atm-data-163", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Concorde Plaza", atmSerial: "New Cairo", atmCode: "EGBW003", atmAddress: "كونكورد بلازا مول" },
    { id: "atm-data-164", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Cairo Festival City", atmSerial: "New Cairo", atmCode: "EGBW022", atmAddress: "كايرو فيستيفال سيتي مول" },
    { id: "atm-data-165", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Point 90", atmSerial: "New Cairo", atmCode: "EGBW042", atmAddress: "بوينت 90 مول" },
    { id: "atm-data-166", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "American University", atmSerial: "New Cairo", atmCode: "EGBW061", atmAddress: "الجامعة الامريكية بالقاهرة" },
    { id: "atm-data-167", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Downtown Katameya", atmSerial: "New Cairo", atmCode: "EGBW081", atmAddress: "داون تاون قطامية" },
    { id: "atm-data-168", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Rehab Branch", atmSerial: "Rehab", atmCode: "EGBN004", atmAddress: "الرحاب، مركز المدينة" },
    { id: "atm-data-169", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Rehab Mall 1", atmSerial: "Rehab", atmCode: "EGBW004", atmAddress: "مول الرحاب 1" },
    { id: "atm-data-170", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Madinaty", atmSerial: "Madinaty", atmCode: "EGBW023", atmAddress: "مدينتي، ارابيسك مول" },
    { id: "atm-data-171", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "الشروق", atmModel: "Shorouk City", atmSerial: "Shorouk", atmCode: "EGBW043", atmAddress: "سكاي بلازا مول" },
    { id: "atm-data-172", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "المعادي", atmModel: "Maadi Branch", atmSerial: "Maadi", atmCode: "EGBN005", atmAddress: "22 شارع 9" },
    { id: "atm-data-173", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "المعادي", atmModel: "Degla Square", atmSerial: "Maadi", atmCode: "EGBW005", atmAddress: "ميدان دجلة" },
    { id: "atm-data-174", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "المعادي", atmModel: "Maadi City Center", atmSerial: "Maadi", atmCode: "EGBW024", atmAddress: "معادي سيتي سنتر" },
    { id: "atm-data-175", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "المنيل", atmModel: "Manial Branch", atmSerial: "Manial", atmCode: "EGBN006", atmAddress: "93 شارع عبد العزيز آل سعود" },
    { id: "atm-data-176", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "القاهرة", city: "جاردن سيتي", atmModel: "Garden City Branch", atmSerial: "Garden City", atmCode: "EGBN007", atmAddress: "10 شارع ابراهيم نجيب" },
    { id: "atm-data-177", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Mohandessin Branch", atmSerial: "Mohandessin", atmCode: "EGBN008", atmAddress: "42 شارع لبنان" },
    { id: "atm-data-178", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Gamet El Dewal", atmSerial: "Mohandessin", atmCode: "EGBW006", atmAddress: "3 شارع جامعة الدول العربية" },
    { id: "atm-data-179", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Platinum Club", atmSerial: "Mohandessin", atmCode: "EGBW025", atmAddress: "النادي البلاتيني" },
    { id: "atm-data-180", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الدقي", atmModel: "Dokki Branch", atmSerial: "Dokki", atmCode: "EGBN009", atmAddress: "23 شارع المساحة" },
    { id: "atm-data-181", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الزمالك", atmModel: "Zamalek Branch", atmSerial: "Zamalek", atmCode: "EGBN010", atmAddress: "157 شارع 26 يوليو" },
    { id: "atm-data-182", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الزمالك", atmModel: "Gezira Club", atmSerial: "Zamalek", atmCode: "EGBW007", atmAddress: "نادي الجزيرة الرياضي" },
    { id: "atm-data-183", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الهرم", atmModel: "Haram Branch", atmSerial: "Haram", atmCode: "EGBN011", atmAddress: "305 شارع الاهرام" },
    { id: "atm-data-184", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "6th of October Branch", atmSerial: "6th of October", atmCode: "EGBN012", atmAddress: "المحور المركزي" },
    { id: "atm-data-185", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "Mall of Arabia", atmSerial: "6th of October", atmCode: "EGBW008", atmAddress: "مول العرب" },
    { id: "atm-data-186", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "Dandy Mall", atmSerial: "6th of October", atmCode: "EGBW026", atmAddress: "داندي مول" },
    { id: "atm-data-187", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "Mall of Egypt", atmSerial: "6th of October", atmCode: "EGBW044", atmAddress: "مول مصر" },
    { id: "atm-data-188", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الشيخ زايد", atmModel: "Sheikh Zayed Branch", atmSerial: "Sheikh Zayed", atmCode: "EGBN013", atmAddress: "زايد 2000" },
    { id: "atm-data-189", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الشيخ زايد", atmModel: "Galleria 40", atmSerial: "Sheikh Zayed", atmCode: "EGBW009", atmAddress: "جاليريا 40" },
    { id: "atm-data-190", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الشيخ زايد", atmModel: "Arkan Plaza", atmSerial: "Sheikh Zayed", atmCode: "EGBW027", atmAddress: "أركان بلازا" },
    { id: "atm-data-191", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الجيزة", city: "الشيخ زايد", atmModel: "Americana Plaza", atmSerial: "Sheikh Zayed", atmCode: "EGBW045", atmAddress: "أمريكانا بلازا" },
    { id: "atm-data-192", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "الاسكندرية", atmModel: "Alexandria Branch", atmSerial: "Alexandria", atmCode: "EGBN014", atmAddress: "51 شارع فؤاد" },
    { id: "atm-data-193", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "الاسكندرية", atmModel: "Kafr Abdo", atmSerial: "Alexandria", atmCode: "EGBW010", atmAddress: "كفر عبده" },
    { id: "atm-data-194", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "الاسكندرية", atmModel: "San Stefano", atmSerial: "Alexandria", atmCode: "EGBW028", atmAddress: "سان ستيفانو جراند بلازا" },
    { id: "atm-data-195", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "الاسكندرية", atmModel: "City Center Alex", atmSerial: "Alexandria", atmCode: "EGBW046", atmAddress: "سيتي سنتر الاسكندرية" },
    { id: "atm-data-196", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "سموحة", atmModel: "Smouha Branch", atmSerial: "Smouha", atmCode: "EGBN015", atmAddress: "14 شارع مايو" },
    { id: "atm-data-197", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاسكندرية", city: "سموحة", atmModel: "Smouha Club", atmSerial: "Smouha", atmCode: "EGBW011", atmAddress: "نادي سموحة الرياضي" },
    { id: "atm-data-198", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الغربية", city: "طنطا", atmModel: "Tanta Branch", atmSerial: "Tanta", atmCode: "EGBN016", atmAddress: "3 شارع الجيش" },
    { id: "atm-data-199", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الدقهلية", city: "المنصورة", atmModel: "Mansoura Branch", atmSerial: "Mansoura", atmCode: "EGBN017", atmAddress: "شارع الجمهورية" },
    { id: "atm-data-200", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "اسيوط", city: "اسيوط", atmModel: "Assiut Branch", atmSerial: "Assiut", atmCode: "EGBN018", atmAddress: "شارع الجمهورية" },
    { id: "atm-data-201", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "البحر الاحمر", city: "الغردقة", atmModel: "Hurghada Branch", atmSerial: "Hurghada", atmCode: "EGBN019", atmAddress: "شارع شيراتون" },
    { id: "atm-data-202", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "البحر الاحمر", city: "الغردقة", atmModel: "Senzo Mall", atmSerial: "Hurghada", atmCode: "EGBW012", atmAddress: "سينزو مول" },
    { id: "atm-data-203", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "جنوب سيناء", city: "شرم الشيخ", atmModel: "Naama Bay Branch", atmSerial: "Sharm El Sheikh", atmCode: "EGBN020", atmAddress: "خليج نعمة" },
    { id: "atm-data-204", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "جنوب سيناء", city: "شرم الشيخ", atmModel: "Soho Square", atmSerial: "Sharm El Sheikh", atmCode: "EGBW013", atmAddress: "سوهو سكوير" },
    { id: "atm-data-205", bankName: "بنك الإمارات دبي الوطني", startDate: "2023-05-11", governorate: "الاقصر", city: "الاقصر", atmModel: "Luxor Branch", atmSerial: "Luxor", atmCode: "EGBN021", atmAddress: "شارع خالد بن الوليد" },
    { id: "atm-data-206", bankName: "بنك الإمارات دبي الوطني", startDate: "2025-05-01", governorate: "أسوان", city: "أسوان", atmModel: "Aswan", atmSerial: "ATM42101", atmCode: "EGBN022", atmAddress: "Aswan" },
    { id: "atm-data-207", bankName: "بنك الإمارات دبي الوطني", startDate: "2025-05-01", governorate: "أسوان", city: "أسوان", atmModel: "Aswan Old Cataract Hotel", atmSerial: "ATM00401", atmCode: "EGBW014", atmAddress: "Aswan Old Cataract Hotel" },
    { id: "atm-data-208", bankName: "بنك الإمارات دبي الوطني", startDate: "2025-05-01", governorate: "أسوان", city: "أسوان", atmModel: "Arab Contractor Club", atmSerial: "ATM00380", atmCode: "EGBW015", atmAddress: "Arab Contractor Club" },
    { id: "atm-data-1", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسيوط", city: "اسيوط", atmModel: "EFIC", atmSerial: "اسيوط", atmCode: "BOAN820", atmAddress: "ناحية والمالية - اسيوط" },
    { id: "atm-data-2", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسيوط", city: "اسيوط", atmModel: "EFIC", atmSerial: "اسيوط", atmCode: "EGA870", atmAddress: "التجاري وفا - بنك مصر" },
    { id: "atm-data-3", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الشرقية", city: "العاشر من رمضان", atmModel: "Olympic Factory", atmSerial: "10th Of Ramadan 2", atmCode: "EGA741", atmAddress: "ناحية 6 قطعة 132,133" },
    { id: "atm-data-4", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "MSA University", atmSerial: "6th Of October", atmCode: "EGA805", atmAddress: "6 اكتوبر MSA جامعه" },
    { id: "atm-data-5", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Misr Free Market", atmSerial: "EGA721", atmCode: "EGA721", atmAddress: "ل العربيه المهندسين 106" },
    { id: "atm-data-6", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسيوط", city: "اسيوط", atmModel: "EFIC", atmSerial: "اسيوط", atmCode: "BOAN820", atmAddress: "ناحية والمالية - اسيوط" },
    { id: "atm-data-7", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسيوط", city: "اسيوط", atmModel: "EFIC", atmSerial: "اسيوط", atmCode: "EGA870", atmAddress: "التجاري وفا - بنك مصر" },
    { id: "atm-data-8", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الشرقية", city: "العاشر من رمضان", atmModel: "Olympic Factory", atmSerial: "10th Of Ramadan 2", atmCode: "EGA741", atmAddress: "ناحية 6 قطعة 132,133" },
    { id: "atm-data-9", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "السادس من اكتوبر", atmModel: "MSA University", atmSerial: "6th Of October", atmCode: "EGA805", atmAddress: "6 اكتوبر MSA جامعه" },
    { id: "atm-data-10", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Misr Free Market", atmSerial: "EGA721", atmCode: "EGA721", atmAddress: "ل العربيه المهندسين 106" },
    { id: "atm-data-11", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "Serag Mall", atmSerial: "Nasr City", atmCode: "EGA745", atmAddress: "مكرم عبيد مدينة نصر" },
    { id: "atm-data-12", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "Heliopolis Club", atmSerial: "Heliopolis", atmCode: "EGA748", atmAddress: "نادي هليوبوليس" },
    { id: "atm-data-13", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الدقي", atmModel: "Dokki Branch", atmSerial: "Dokki", atmCode: "EGA723", atmAddress: "فرع الدقي" },
    { id: "atm-data-14", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الزمالك", atmModel: "Zamalek Club", atmSerial: "Zamalek", atmCode: "EGA749", atmAddress: "نادي الزمالك" },
    { id: "atm-data-15", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "سموحة", atmModel: "Smouha Club", atmSerial: "Smouha", atmCode: "EGA811", atmAddress: "نادي سموحة" },
    { id: "atm-data-16", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "شبرا", atmModel: "Shoubra Branch", atmSerial: "Shoubra", atmCode: "EGA750", atmAddress: "فرع شبرا" },
    { id: "atm-data-17", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "حلوان", atmModel: "Helwan University", atmSerial: "Helwan", atmCode: "EGA751", atmAddress: "جامعة حلوان" },
    { id: "atm-data-18", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الهرم", atmModel: "Pyramids Heights", atmSerial: "Haram", atmCode: "EGA724", atmAddress: "هضبة الاهرام" },
    { id: "atm-data-19", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "المقطم", atmModel: "Mokattam Club", atmSerial: "Mokattam", atmCode: "EGA752", atmAddress: "نادي المقطم" },
    { id: "atm-data-20", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الرحاب", atmModel: "Rehab Mall 2", atmSerial: "Rehab", atmCode: "EGA753", atmAddress: "مول الرحاب 2" },
    { id: "atm-data-21", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينتي", atmModel: "Madinaty Open Air Mall", atmSerial: "Madinaty", atmCode: "EGA754", atmAddress: "مدينتي اوبن اير مول" },
    { id: "atm-data-22", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "بنها", atmModel: "Banha University", atmSerial: "Banha", atmCode: "EGA760", atmAddress: "جامعة بنها" },
    { id: "atm-data-23", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنوفية", city: "شبين الكوم", atmModel: "Menoufia University", atmSerial: "Shebin El Kom", atmCode: "EGA761", atmAddress: "جامعة المنوفية" },
    { id: "atm-data-24", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الغربية", city: "طنطا", atmModel: "Tanta Club", atmSerial: "Tanta", atmCode: "EGA762", atmAddress: "نادي طنطا" },
    { id: "atm-data-25", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الدقهلية", city: "المنصورة", atmModel: "Mansoura University", atmSerial: "Mansoura", atmCode: "EGA763", atmAddress: "جامعة المنصورة" },
    { id: "atm-data-26", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحيرة", city: "دمنهور", atmModel: "Damanhour Branch", atmSerial: "Damanhour", atmCode: "EGA764", atmAddress: "فرع دمنهور" },
    { id: "atm-data-27", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "كفر الشيخ", city: "كفر الشيخ", atmModel: "Kafr El Sheikh University", atmSerial: "Kafr El Sheikh", atmCode: "EGA765", atmAddress: "جامعة كفر الشيخ" },
    { id: "atm-data-28", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "دمياط", city: "دمياط", atmModel: "Damietta Port", atmSerial: "Damietta", atmCode: "EGA766", atmAddress: "ميناء دمياط" },
    { id: "atm-data-29", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "بورسعيد", city: "بورسعيد", atmModel: "Port Said Branch", atmSerial: "Port Said", atmCode: "EGA767", atmAddress: "فرع بورسعيد" },
    { id: "atm-data-30", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسماعيلية", city: "الاسماعيلية", atmModel: "Suez Canal University", atmSerial: "Ismailia", atmCode: "EGA768", atmAddress: "جامعة قناة السويس" },
    { id: "atm-data-31", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "السويس", city: "السويس", atmModel: "Suez Branch", atmSerial: "Suez", atmCode: "EGA769", atmAddress: "فرع السويس" },
    { id: "atm-data-32", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "شمال سيناء", city: "العريش", atmModel: "Arish Branch", atmSerial: "Arish", atmCode: "EGA770", atmAddress: "فرع العريش" },
    { id: "atm-data-33", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "جنوب سيناء", city: "شرم الشيخ", atmModel: "Naama Bay", atmSerial: "Sharm El Sheikh", atmCode: "EGA771", atmAddress: "خليج نعمة" },
    { id: "atm-data-34", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحر الاحمر", city: "الغردقة", atmModel: "Hurghada Marina", atmSerial: "Hurghada", atmCode: "EGA772", atmAddress: "مارينا الغردقة" },
    { id: "atm-data-35", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الفيوم", city: "الفيوم", atmModel: "Fayoum University", atmSerial: "Fayoum", atmCode: "EGA780", atmAddress: "جامعة الفيوم" },
    { id: "atm-data-36", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "بني سويف", city: "بني سويف", atmModel: "Beni Suef University", atmSerial: "Beni Suef", atmCode: "EGA781", atmAddress: "جامعة بني سويف" },
    { id: "atm-data-37", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنيا", city: "المنيا", atmModel: "Minya University", atmSerial: "Minya", atmCode: "EGA782", atmAddress: "جامعة المنيا" },
    { id: "atm-data-38", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "قنا", city: "قنا", atmModel: "South Valley University", atmSerial: "Qena", atmCode: "EGA784", atmAddress: "جامعة جنوب الوادي" },
    { id: "atm-data-39", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "سوهاج", city: "سوهاج", atmModel: "Sohag University", atmSerial: "Sohag", atmCode: "EGA783", atmAddress: "جامعة سوهاج" },
    { id: "atm-data-40", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاقصر", city: "الاقصر", atmModel: "Luxor Temple", atmSerial: "Luxor", atmCode: "EGA785", atmAddress: "معبد الاقصر" },
    { id: "atm-data-41", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسوان", city: "اسوان", atmModel: "Aswan High Dam", atmSerial: "Aswan", atmCode: "EGA786", atmAddress: "السد العالي" },
    { id: "atm-data-42", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الوادي الجديد", city: "الخارجة", atmModel: "Kharga Oasis", atmSerial: "New Valley", atmCode: "EGA787", atmAddress: "واحة الخارجة" },
    { id: "atm-data-43", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "مطروح", city: "مرسى مطروح", atmModel: "Marsa Matruh Beach", atmSerial: "Matruh", atmCode: "EGA773", atmAddress: "شاطئ مرسى مطروح" },
    { id: "atm-data-44", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "وسط البلد", atmModel: "Talaat Harb Sq.", atmSerial: "Downtown", atmCode: "EGA701", atmAddress: "ميدان طلعت حرب" },
    { id: "atm-data-45", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الزمالك", atmModel: "Gezira Club", atmSerial: "Gezira", atmCode: "EGA725", atmAddress: "نادي الجزيرة" },
    { id: "atm-data-46", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "ستانلي", atmModel: "Stanley Bridge", atmSerial: "Stanley", atmCode: "EGA812", atmAddress: "كوبري ستانلي" },
    { id: "atm-data-47", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "التجمع الخامس", atmModel: "Cairo Festival City", atmSerial: "5th Settlement", atmCode: "EGA755", atmAddress: "كايرو فيستيفال سيتي" },
    { id: "atm-data-48", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الشيخ زايد", atmModel: "Mall of Arabia", atmSerial: "Sheikh Zayed", atmCode: "EGA726", atmAddress: "مول العرب" },
    { id: "atm-data-49", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "المعادي", atmModel: "Maadi Grand Mall", atmSerial: "Maadi", atmCode: "EGA756", atmAddress: "المعادي جراند مول" },
    { id: "atm-data-50", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الشرقية", city: "الزقازيق", atmModel: "Zagazig University", atmSerial: "Zagazig", atmCode: "EGA760-2", atmAddress: "جامعة الزقازيق" },
    { id: "atm-data-51", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "ميامي", atmModel: "Miami Beach", atmSerial: "Miami", atmCode: "EGA813", atmAddress: "شاطئ ميامي" },
    { id: "atm-data-52", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "المهندسين", atmModel: "Shooting Club", atmSerial: "Mohandessin", atmCode: "EGA722", atmAddress: "نادي الصيد" },
    { id: "atm-data-53", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر الجديدة", atmModel: "City Stars Mall", atmSerial: "Heliopolis", atmCode: "EGA747", atmAddress: "سيتي ستارز مول" },
    { id: "atm-data-54", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مدينة نصر", atmModel: "Genena Mall", atmSerial: "Nasr City", atmCode: "EGA746", atmAddress: "جنينة مول" },
    { id: "atm-data-55", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "6 اكتوبر", atmModel: "Mall of Egypt", atmSerial: "6th of October", atmCode: "EGA806", atmAddress: "مول مصر" },
    { id: "atm-data-56", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "القاهرة الجديدة", atmModel: "Point 90 Mall", atmSerial: "New Cairo", atmCode: "EGA757", atmAddress: "بوينت 90 مول" },
    { id: "atm-data-57", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "سيدي جابر", atmModel: "Sidi Gaber Station", atmSerial: "Sidi Gaber", atmCode: "EGA814", atmAddress: "محطة سيدي جابر" },
    { id: "atm-data-58", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "جاردن سيتي", atmModel: "Four Seasons Hotel", atmSerial: "Garden City", atmCode: "EGA702", atmAddress: "فندق فور سيزونز" },
    { id: "atm-data-59", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "القرية الذكية", atmModel: "Smart Village", atmSerial: "Smart Village", atmCode: "EGA727", atmAddress: "القرية الذكية" },
    { id: "atm-data-60", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الأزهر", atmModel: "Al-Azhar University", atmSerial: "Al-Azhar", atmCode: "EGA703", atmAddress: "جامعة الأزهر" },
    { id: "atm-data-61", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "عين شمس", atmModel: "Ain Shams University", atmSerial: "Ain Shams", atmCode: "EGA758", atmAddress: "جامعة عين شمس" },
    { id: "atm-data-62", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "فيصل", atmModel: "Faisal Islamic Bank", atmSerial: "Faisal", atmCode: "EGA728", atmAddress: "بنك فيصل الاسلامي" },
    { id: "atm-data-63", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "المنتزة", atmModel: "Montaza Palace", atmSerial: "Montaza", atmCode: "EGA815", atmAddress: "قصر المنتزة" },
    { id: "atm-data-64", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "العباسية", atmModel: "Abbassia Branch", atmSerial: "Abbassia", atmCode: "EGA759", atmAddress: "فرع العباسية" },
    { id: "atm-data-65", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "رمسيس", atmModel: "Ramses Hilton", atmSerial: "Ramses", atmCode: "EGA704", atmAddress: "هيلتون رمسيس" },
    { id: "atm-data-66", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "امبابة", atmModel: "Imbaba Branch", atmSerial: "Imbaba", atmCode: "EGA729", atmAddress: "فرع امبابة" },
    { id: "atm-data-67", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "العجمي", atmModel: "Agami Branch", atmSerial: "Agami", atmCode: "EGA816", atmAddress: "فرع العجمي" },
    { id: "atm-data-68", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الجمالية", atmModel: "Khan el-Khalili", atmSerial: "Gamaleya", atmCode: "EGA705", atmAddress: "خان الخليلي" },
    { id: "atm-data-69", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "بولاق الدكرور", atmModel: "Bulaq El Dakrour", atmSerial: "Bulaq", atmCode: "EGA730", atmAddress: "بولاق الدكرور" },
    { id: "atm-data-70", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الساحل", atmModel: "Sahel Branch", atmSerial: "Sahel", atmCode: "EGA760-3", atmAddress: "فرع الساحل" },
    { id: "atm-data-71", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "العجوزة", atmModel: "Agouza Hospital", atmSerial: "Agouza", atmCode: "EGA731", atmAddress: "مستشفى العجوزة" },
    { id:"atm-data-72", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الوايلي", atmModel: "Wayli Branch", atmSerial: "Wayli", atmCode: "EGA760-4", atmAddress: "فرع الوايلي" },
    { id: "atm-data-73", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسكندرية", city: "برج العرب", atmModel: "Borg El Arab Airport", atmSerial: "Borg El Arab", atmCode: "EGA817", atmAddress: "مطار برج العرب" },
    { id: "atm-data-74", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الشرابية", atmModel: "Sharabia Branch", atmSerial: "Sharabia", atmCode: "EGA760-5", atmAddress: "فرع الشرابية" },
    { id: "atm-data-75", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "المرج", atmModel: "El Marg Branch", atmSerial: "El Marg", atmCode: "EGA760-6", atmAddress: "فرع المرج" },
    { id: "atm-data-76", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "السلام", atmModel: "El Salam City", atmSerial: "El Salam", atmCode: "EGA760-7", atmAddress: "مدينة السلام" },
    { id: "atm-data-77", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "مصر القديمة", atmModel: "Coptic Cairo", atmSerial: "Old Cairo", atmCode: "EGA706", atmAddress: "مصر القديمة" },
    { id: "atm-data-78", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الحوامدية", atmModel: "Hawamdeya Branch", atmSerial: "Hawamdeya", atmCode: "EGA732", atmAddress: "فرع الحوامدية" },
    { id: "atm-data-79", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "البدرشين", atmModel: "Badrashein Branch", atmSerial: "Badrashein", atmCode: "EGA733", atmAddress: "فرع البدرشين" },
    { id: "atm-data-80", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "العياط", atmModel: "Ayat Branch", atmSerial: "Ayat", atmCode: "EGA734", atmAddress: "فرع العياط" },
    { id: "atm-data-81", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "أوسيم", atmModel: "Oseem Branch", atmSerial: "Oseem", atmCode: "EGA735", atmAddress: "فرع أوسيم" },
    { id: "atm-data-82", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "شبرا الخيمة", atmModel: "Shubra El Kheima", atmSerial: "Shubra El Kheima", atmCode: "EGA760-8", atmAddress: "شبرا الخيمة" },
    { id: "atm-data-83", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "الخانكة", atmModel: "Khanka Branch", atmSerial: "Khanka", atmCode: "EGA760-9", atmAddress: "فرع الخانكة" },
    { id: "atm-data-84", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "قليوب", atmModel: "Qalyub Branch", atmSerial: "Qalyub", atmCode: "EGA760-10", atmAddress: "فرع قليوب" },
    { id: "atm-data-85", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنوفية", city: "السادات", atmModel: "Sadat City", atmSerial: "Sadat", atmCode: "EGA761-2", atmAddress: "مدينة السادات" },
    { id: "atm-data-86", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنوفية", city: "أشمون", atmModel: "Ashmoun Branch", atmSerial: "Ashmoun", atmCode: "EGA761-3", atmAddress: "فرع أشمون" },
    { id: "atm-data-87", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الغربية", city: "المحلة الكبرى", atmModel: "Mahalla Club", atmSerial: "Mahalla", atmCode: "EGA762-2", atmAddress: "نادي المحلة" },
    { id: "atm-data-88", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الغربية", city: "كفر الزيات", atmModel: "Kafr El Zayat", atmSerial: "Kafr El Zayat", atmCode: "EGA762-3", atmAddress: "كفر الزيات" },
    { id: "atm-data-89", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الدقهلية", city: "ميت غمر", atmModel: "Mit Ghamr Branch", atmSerial: "Mit Ghamr", atmCode: "EGA763-2", atmAddress: "فرع ميت غمر" },
    { id: "atm-data-90", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الدقهلية", city: "بلقاس", atmModel: "Belqas Branch", atmSerial: "Belqas", atmCode: "EGA763-3", atmAddress: "فرع بلقاس" },
    { id: "atm-data-91", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحيرة", city: "رشيد", atmModel: "Rosetta Branch", atmSerial: "Rosetta", atmCode: "EGA764-2", atmAddress: "فرع رشيد" },
    { id: "atm-data-92", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحيرة", city: "ادكو", atmModel: "Edko Branch", atmSerial: "Edko", atmCode: "EGA764-3", atmAddress: "فرع ادكو" },
    { id: "atm-data-93", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "كفر الشيخ", city: "دسوق", atmModel: "Desouk Branch", atmSerial: "Desouk", atmCode: "EGA765-2", atmAddress: "فرع دسوق" },
    { id: "atm-data-94", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "دمياط", city: "فارسكور", atmModel: "Faraskur Branch", atmSerial: "Faraskur", atmCode: "EGA766-2", atmAddress: "فرع فارسكور" },
    { id: "atm-data-95", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "بورسعيد", city: "بورفؤاد", atmModel: "Port Fouad", atmSerial: "Port Fouad", atmCode: "EGA767-2", atmAddress: "بورفؤاد" },
    { id: "atm-data-96", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسماعيلية", city: "القنطرة شرق", atmModel: "Qantara Sharq", atmSerial: "Qantara", atmCode: "EGA768-2", atmAddress: "القنطرة شرق" },
    { id: "atm-data-97", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "السويس", city: "عتاقة", atmModel: "Attaka Port", atmSerial: "Attaka", atmCode: "EGA769-2", atmAddress: "ميناء عتاقة" },
    { id: "atm-data-98", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "شمال سيناء", city: "بئر العبد", atmModel: "Bir al-Abed", atmSerial: "Bir al-Abed", atmCode: "EGA770-2", atmAddress: "بئر العبد" },
    { id: "atm-data-99", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "جنوب سيناء", city: "دهب", atmModel: "Dahab Bay", atmSerial: "Dahab", atmCode: "EGA771-2", atmAddress: "خليج دهب" },
    { id: "atm-data-100", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحر الاحمر", city: "سفاجا", atmModel: "Safaga Port", atmSerial: "Safaga", atmCode: "EGA772-2", atmAddress: "ميناء سفاجا" },
    { id: "atm-data-101", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الفيوم", city: "سنورس", atmModel: "Snores Branch", atmSerial: "Snores", atmCode: "EGA780-2", atmAddress: "فرع سنورس" },
    { id: "atm-data-102", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "بني سويف", city: "الواسطى", atmModel: "Wasta Branch", atmSerial: "Wasta", atmCode: "EGA781-2", atmAddress: "فرع الواسطى" },
    { id: "atm-data-103", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنيا", city: "ملوي", atmModel: "Mallawi Branch", atmSerial: "Mallawi", atmCode: "EGA782-2", atmAddress: "فرع ملوي" },
    { id: "atm-data-104", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "سوهاج", city: "أخميم", atmModel: "Akhmim Branch", atmSerial: "Akhmim", atmCode: "EGA783-2", atmAddress: "فرع أخميم" },
    { id: "atm-data-105", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "قنا", city: "نجع حمادي", atmModel: "Nagaa Hammadi", atmSerial: "Nagaa Hammadi", atmCode: "EGA784-2", atmAddress: "نجع حمادي" },
    { id: "atm-data-106", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاقصر", city: "الكرنك", atmModel: "Karnak Temple", atmSerial: "Karnak", atmCode: "EGA785-2", atmAddress: "معبد الكرنك" },
    { id: "atm-data-107", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسوان", city: "كوم امبو", atmModel: "Kom Ombo Temple", atmSerial: "Kom Ombo", atmCode: "EGA786-2", atmAddress: "معبد كوم امبو" },
    { id: "atm-data-108", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الوادي الجديد", city: "الداخلة", atmModel: "Dakhla Oasis", atmSerial: "Dakhla", atmCode: "EGA787-2", atmAddress: "واحة الداخلة" },
    { id: "atm-data-109", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "مطروح", city: "العلمين", atmModel: "Alamein Military Museum", atmSerial: "Alamein", atmCode: "EGA773-2", atmAddress: "متحف العلمين العسكري" },
    { id: "atm-data-110", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "باب الشعرية", atmModel: "Bab El Shaaria", atmSerial: "Bab El Shaaria", atmCode: "EGA707", atmAddress: "باب الشعرية" },
    { id: "atm-data-111", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "عابدين", atmModel: "Abdeen Palace", atmSerial: "Abdeen", atmCode: "EGA708", atmAddress: "قصر عابدين" },
    { id: "atm-data-112", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "السيدة زينب", atmModel: "Sayeda Zeinab", atmSerial: "Sayeda Zeinab", atmCode: "EGA709", atmAddress: "السيدة زينب" },
    { id: "atm-data-113", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الظاهر", atmModel: "Daher Branch", atmSerial: "Daher", atmCode: "EGA710", atmAddress: "فرع الظاهر" },
    { id: "atm-data-114", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "كرداسة", atmModel: "Kerdasa Branch", atmSerial: "Kerdasa", atmCode: "EGA736", atmAddress: "فرع كرداسة" },
    { id: "atm-data-115", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "منشأة القناطر", atmModel: "Manshiyat al Qanatir", atmSerial: "Manshiyat", atmCode: "EGA737", atmAddress: "منشأة القناطر" },
    { id: "atm-data-116", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "الصف", atmModel: "Saf Branch", atmSerial: "Saf", atmCode: "EGA738", atmAddress: "فرع الصف" },
    { id: "atm-data-117", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "أطفيح", atmModel: "Atfih Branch", atmSerial: "Atfih", atmCode: "EGA739", atmAddress: "فرع أطفيح" },
    { id: "atm-data-118", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "طوخ", atmModel: "Toukh Branch", atmSerial: "Toukh", atmCode: "EGA760-11", atmAddress: "فرع طوخ" },
    { id: "atm-data-119", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القليوبية", city: "كفر شكر", atmModel: "Kafr Shukr", atmSerial: "Kafr Shukr", atmCode: "EGA760-12", atmAddress: "كفر شكر" },
    { id: "atm-data-120", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنوفية", city: "تلا", atmModel: "Tala Branch", atmSerial: "Tala", atmCode: "EGA761-4", atmAddress: "فرع تلا" },
    { id: "atm-data-121", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنوفية", city: "الباجور", atmModel: "Bagour Branch", atmSerial: "Bagour", atmCode: "EGA761-5", atmAddress: "فرع الباجور" },
    { id: "atm-data-122", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الغربية", city: "سمنود", atmModel: "Samanoud Branch", atmSerial: "Samanoud", atmCode: "EGA762-4", atmAddress: "فرع سمنود" },
    { id: "atm-data-123", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الغربية", city: "زفتى", atmModel: "Zifta Branch", atmSerial: "Zifta", atmCode: "EGA762-5", atmAddress: "فرع زفتى" },
    { id: "atm-data-124", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الدقهلية", city: "السنبلاوين", atmModel: "Sinbillawain", atmSerial: "Sinbillawain", atmCode: "EGA763-4", atmAddress: "السنبلاوين" },
    { id: "atm-data-125", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الدقهلية", city: "دكرنس", atmModel: "Dekernes Branch", atmSerial: "Dekernes", atmCode: "EGA763-5", atmAddress: "فرع دكرنس" },
    { id: "atm-data-126", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحيرة", city: "كوم حمادة", atmModel: "Kom Hamada", atmSerial: "Kom Hamada", atmCode: "EGA764-4", atmAddress: "كوم حمادة" },
    { id: "atm-data-127", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحيرة", city: "ايتاي البارود", atmModel: "Itay El Baroud", atmSerial: "Itay El Baroud", atmCode: "EGA764-5", atmAddress: "ايتاي البارود" },
    { id: "atm-data-128", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "كفر الشيخ", city: "بيلا", atmModel: "Bella Branch", atmSerial: "Bella", atmCode: "EGA765-3", atmAddress: "فرع بيلا" },
    { id: "atm-data-129", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "كفر الشيخ", city: "الحامول", atmModel: "Hamoul Branch", atmSerial: "Hamoul", atmCode: "EGA765-4", atmAddress: "فرع الحامول" },
    { id: "atm-data-130", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "دمياط", city: "الزرقا", atmModel: "Zarqa Branch", atmSerial: "Zarqa", atmCode: "EGA766-3", atmAddress: "فرع الزرقا" },
    { id: "atm-data-131", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "دمياط", city: "كفر سعد", atmModel: "Kafr Saad", atmSerial: "Kafr Saad", atmCode: "EGA766-4", atmAddress: "كفر سعد" },
    { id: "atm-data-132", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسماعيلية", city: "التل الكبير", atmModel: "Tel El Kebir", atmSerial: "Tel El Kebir", atmCode: "EGA768-3", atmAddress: "التل الكبير" },
    { id: "atm-data-133", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاسماعيلية", city: "فايد", atmModel: "Fayed Branch", atmSerial: "Fayed", atmCode: "EGA768-4", atmAddress: "فرع فايد" },
    { id: "atm-data-134", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "شمال سيناء", city: "رفح", atmModel: "Rafah Crossing", atmSerial: "Rafah", atmCode: "EGA770-3", atmAddress: "معبر رفح" },
    { id: "atm-data-135", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "جنوب سيناء", city: "نويبع", atmModel: "Nuweiba Port", atmSerial: "Nuweiba", atmCode: "EGA771-3", atmAddress: "ميناء نويبع" },
    { id: "atm-data-136", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "البحر الاحمر", city: "مرسى علم", atmModel: "Marsa Alam Airport", atmSerial: "Marsa Alam", atmCode: "EGA772-3", atmAddress: "مطار مرسى علم" },
    { id: "atm-data-137", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الفيوم", city: "اطسا", atmModel: "Etsa Branch", atmSerial: "Etsa", atmCode: "EGA780-3", atmAddress: "فرع اطسا" },
    { id: "atm-data-138", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "بني سويف", city: "ناصر", atmModel: "Nasser Branch", atmSerial: "Nasser", atmCode: "EGA781-3", atmAddress: "فرع ناصر" },
    { id: "atm-data-139", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "المنيا", city: "سمالوط", atmModel: "Samalut Branch", atmSerial: "Samalut", atmCode: "EGA782-3", atmAddress: "فرع سمالوط" },
    { id: "atm-data-140", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "سوهاج", city: "جرجا", atmModel: "Girga Branch", atmSerial: "Girga", atmCode: "EGA783-3", atmAddress: "فرع جرجا" },
    { id: "atm-data-141", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "قنا", city: "قفط", atmModel: "Qift Branch", atmSerial: "Qift", atmCode: "EGA784-3", atmAddress: "فرع قفط" },
    { id: "atm-data-142", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الاقصر", city: "اسنا", atmModel: "Esna Lock", atmSerial: "Esna", atmCode: "EGA785-3", atmAddress: "قناطر اسنا" },
    { id: "atm-data-143", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "اسوان", city: "ادفو", atmModel: "Edfu Temple", atmSerial: "Edfu", atmCode: "EGA786-3", atmAddress: "معبد ادفو" },
    { id: "atm-data-144", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الوادي الجديد", city: "الفرافرة", atmModel: "Farafra Oasis", atmSerial: "Farafra", atmCode: "EGA787-3", atmAddress: "واحة الفرافرة" },
    { id: "atm-data-145", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "مطروح", city: "سيوة", atmModel: "Siwa Oasis", atmSerial: "Siwa", atmCode: "EGA773-3", atmAddress: "واحة سيوة" },
    { id: "atm-data-146", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "القطامية", atmModel: "Katameya Heights", atmSerial: "Katameya", atmCode: "EGA757-2", atmAddress: "قطامية هايتس" },
    { id: "atm-data-147", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "الشروق", atmModel: "El Shorouk City", atmSerial: "El Shorouk", atmCode: "EGA757-3", atmAddress: "مدينة الشروق" },
    { id: "atm-data-148", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "بدر", atmModel: "Badr City", atmSerial: "Badr", atmCode: "EGA757-4", atmAddress: "مدينة بدر" },
    { id: "atm-data-149", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "القاهرة", city: "العاصمة الإدارية", atmModel: "New Capital", atmSerial: "New Capital", atmCode: "EGA757-5", atmAddress: "العاصمة الإدارية الجديدة" },
    { id: "atm-data-150", bankName: "بنك مصر", startDate: "2023-05-11", governorate: "الجيزة", city: "حدائق اكتوبر", atmModel: "October Gardens", atmSerial: "October Gardens", atmCode: "EGA807", atmAddress: "حدائق اكتوبر" }
];

export const workPlans: WorkPlan[] = [
    {
        id: 'wp-001',
        bankName: 'البنك العربي',
        startDate: '2025-02-10',
        endDate: '2025-02-10',
        governorate: 'القاهرة',
        city: 'الخليفة و المقطم',
        statement: 'يوسف'
    },
    {
        id: 'wp-002',
        bankName: 'بنك الإسكندرية',
        startDate: '2025-06-10',
        endDate: '2025-06-10',
        governorate: 'الغربية',
        city: 'المحلة الكبرى - حي أول',
        statement: 'محمد سلطان'
    },
    {
        id: 'wp-003',
        bankName: 'البنك العربي',
        startDate: '2025-03-26',
        endDate: '2025-03-26',
        governorate: 'القاهرة',
        city: 'Zamalek',
        statement: 'yousef'
    },
    {
        id: 'wp-004',
        bankName: 'البنك العربي',
        startDate: '2025-03-08',
        endDate: '2025-03-08',
        governorate: 'الشرقية',
        city: 'العاشر من رمضان',
        statement: 'yousef'
    },
    {
        id: 'wp-005',
        bankName: 'البنك العربي',
        startDate: '2025-03-15',
        endDate: '2025-03-15',
        governorate: 'القاهرة',
        city: 'مدينة نصر - غرب',
        statement: 'yousef'
    }
];

export const governorates: Governorate[] = [
  { id: '1', nameAr: 'القاهرة', nameEn: 'Cairo', cities: [
      { id: 'c101', nameAr: '15 مايو', nameEn: '15 May' },
      { id: 'c102', nameAr: 'الازبكية', nameEn: 'Azbakeya' },
      { id: 'c103', nameAr: 'البساتين ودار السلام', nameEn: 'Basatin & Dar El-Salam' },
      { id: 'c104', nameAr: 'التبين', nameEn: 'Tebin' },
      { id: 'c105', nameAr: 'الخليفة والمقطم', nameEn: 'Khalifa & Mokattam' },
      { id: 'c106', nameAr: 'الدرب الاحمر', nameEn: 'Darb al-Ahmar' },
      { id: 'c107', nameAr: 'الزاوية الحمراء', nameEn: 'Zawya al-Hamra' },
      { id: 'c108', nameAr: 'الزيتون', nameEn: 'Zaytoun' },
      { id: 'c109', nameAr: 'الساحل', nameEn: 'Sahel' },
      { id: 'c110', nameAr: 'السلام', nameEn: 'Salam' },
      { id: 'c111', nameAr: 'السيدة زينب', nameEn: 'Sayeda Zeinab' },
      { id: 'c112', nameAr: 'الشرابية', nameEn: 'Sharabiya' },
      { id: 'c113', nameAr: 'مدينة الشروق', nameEn: 'Shorouk' },
      { id: 'c114', nameAr: 'الظاهر', nameEn: 'Dhaher' },
      { id: 'c115', nameAr: 'العاصمة الادارية', nameEn: 'New Capital' },
      { id: 'c116', nameAr: 'المرج', nameEn: 'Marg' },
      { id: 'c117', nameAr: 'المعادى', nameEn: 'Maadi' },
      { id: 'c118', nameAr: 'المعصرة', nameEn: 'Maasara' },
      { id: 'c119', nameAr: 'المنيل', nameEn: 'Manyal' },
      { id: 'c120', nameAr: 'الموسكى', nameEn: 'Moski' },
      { id: 'c121', nameAr: 'النزهة', nameEn: 'Nouzha' },
      { id: 'c122', nameAr: 'الوايلى', nameEn: 'Wayli' },
      { id: 'c123', nameAr: 'باب الشعرية', nameEn: 'Bab al-Shereia' },
      { id: 'c124', nameAr: 'بدر', nameEn: 'Badr' },
      { id: 'c125', nameAr: 'جاردن سيتى', nameEn: 'Garden City' },
      { id: 'c126', nameAr: 'حلوان', nameEn: 'Helwan' },
      { id: 'c127', nameAr: 'وسط البلد', nameEn: 'Downtown' },
      { id: 'c128', nameAr: 'شبرا', nameEn: 'Shoubra' },
      { id: 'c129', nameAr: 'طره', nameEn: 'Tora' },
      { id: 'c130', nameAr: 'عابدين', nameEn: 'Abdeen' },
      { id: 'c131', nameAr: 'عين شمس', nameEn: 'Ain Shams' },
      { id: 'c132', nameAr: 'مدينة نصر', nameEn: 'Nasr City' },
      { id: 'c133', nameAr: 'مصر الجديدة', nameEn: 'Heliopolis' },
      { id: 'c134', nameAr: 'مصر القديمة', nameEn: 'Old Cairo' },
      { id: 'c135', nameAr: 'منشأة ناصر', nameEn: 'Manshiyat Naser' },
      { id: 'c136', nameAr: 'القاهرة الجديدة', nameEn: 'New Cairo' },
  ]},
  { id: '2', nameAr: 'الجيزة', nameEn: 'Giza', cities: [
      { id: 'c201', nameAr: 'العجوزة', nameEn: 'Agouza' },
      { id: 'c202', nameAr: 'الدقى', nameEn: 'Dokki' },
      { id: 'c219', nameAr: 'الزمالك', nameEn: 'Zamalek' },
      { id: 'c203', nameAr: 'الهرم', nameEn: 'Haram' },
      { id: 'c204', nameAr: 'الوراق', nameEn: 'Warraq' },
      { id: 'c205', nameAr: 'امبابة', nameEn: 'Imbaba' },
      { id: 'c206', nameAr: 'بولاق الدكرور', nameEn: 'Bulaq ad-Dakrur' },
      { id: 'c207', nameAr: 'الجيزة', nameEn: 'Giza' },
      { id: 'c208', nameAr: 'الحوامدية', nameEn: 'Hawamdeya' },
      { id: 'c209', nameAr: 'البدرشين', nameEn: 'Badrashin' },
      { id: 'c210', nameAr: 'العياط', nameEn: 'Ayat' },
      { id: 'c211', nameAr: 'منشأة القناطر', nameEn: 'Manshiyat al-Qanatir' },
      { id: 'c212', nameAr: 'اوسيم', nameEn: 'Oseem' },
      { id: 'c213', nameAr: 'كرداسة', nameEn: 'Kerdasa' },
      { id: 'c214', nameAr: 'الصف', nameEn: 'Saf' },
      { id: 'c215', nameAr: 'اطفيح', nameEn: 'Atfeh' },
      { id: 'c216', nameAr: 'الواحات البحرية', nameEn: 'Bahariya Oasis' },
      { id: 'c217', nameAr: 'الشيخ زايد', nameEn: 'Sheikh Zayed' },
      { id: 'c218', nameAr: 'السادس من اكتوبر', nameEn: '6th of October' },
  ]},
  { id: '3', nameAr: 'الإسكندرية', nameEn: 'Alexandria', cities: [
      { id: 'c301', nameAr: 'المنتزة', nameEn: 'Montaza' },
      { id: 'c302', nameAr: 'شرق', nameEn: 'East' },
      { id: 'c303', nameAr: 'وسط', nameEn: 'Center' },
      { id: 'c304', nameAr: 'غرب', nameEn: 'West' },
      { id: 'c305', nameAr: 'الجمرك', nameEn: 'Gomrok' },
      { id: 'c306', nameAr: 'العجمى', nameEn: 'Agami' },
      { id: 'c307', nameAr: 'العامرية', nameEn: 'Amreya' },
      { id: 'c308', nameAr: 'برج العرب', nameEn: 'Borg El Arab' },
      { id: 'c309', nameAr: 'ميامي', nameEn: 'Miami' },
      { id: 'c310', nameAr: 'ستانلي', nameEn: 'Stanley' },
      { id: 'c311', nameAr: 'سيدي جابر', nameEn: 'Sidi Gaber' },
      { id: 'c312', nameAr: 'سموحة', nameEn: 'Smouha' },
  ]},
  { id: '4', nameAr: 'الإسماعيلية', nameEn: 'Ismailia', cities: [
      { id: 'c401', nameAr: 'الاسماعيلية', nameEn: 'Ismailia' },
      { id: 'c402', nameAr: 'فايد', nameEn: 'Fayed' },
      { id: 'c403', nameAr: 'القنطرة شرق', nameEn: 'Qantara Sharq' },
      { id: 'c404', nameAr: 'القنطرة غرب', nameEn: 'Qantara Gharb' },
      { id: 'c405', nameAr: 'التل الكبير', nameEn: 'Tel el-Kebir' },
      { id: 'c406', nameAr: 'ابو صوير', nameEn: 'Abu Suweir' },
      { id: 'c407', nameAr: 'القصاصين', nameEn: 'Qassasin' },
  ]},
  { id: '5', nameAr: 'أسوان', nameEn: 'Aswan', cities: [
      { id: 'c501', nameAr: 'اسوان', nameEn: 'Aswan' },
      { id: 'c502', nameAr: 'ادفو', nameEn: 'Edfu' },
      { id: 'c503', nameAr: 'كوم امبو', nameEn: 'Kom Ombo' },
      { id: 'c504', nameAr: 'دراو', nameEn: 'Daraw' },
      { id: 'c505', nameAr: 'نصر', nameEn: 'Nasr' },
  ]},
  { id: '6', nameAr: 'أسيوط', nameEn: 'Asyut', cities: [
      { id: 'c601', nameAr: 'اسيوط', nameEn: 'Asyut' },
      { id: 'c602', nameAr: 'ديروط', nameEn: 'Dayrout' },
      { id: 'c603', nameAr: 'القوصية', nameEn: 'Qusiya' },
      { id: 'c604', nameAr: 'ابنوب', nameEn: 'Abnoub' },
      { id: 'c605', nameAr: 'منفلوط', nameEn: 'Manfalut' },
      { id: 'c606', nameAr: 'ابو تيج', nameEn: 'Abu Tig' },
      { id: 'c607', nameAr: 'الغنايم', nameEn: 'Ghanayem' },
      { id: 'c608', nameAr: 'ساحل سليم', nameEn: 'Sahel Selim' },
      { id: 'c609', nameAr: 'البدارى', nameEn: 'Badari' },
      { id: 'c610', nameAr: 'صدفا', nameEn: 'Sidfa' },
      { id: 'c611', nameAr: 'الفتح', nameEn: 'Fath' },
  ]},
  { id: '7', nameAr: 'الأقصر', nameEn: 'Luxor', cities: [
      { id: 'c701', nameAr: 'الاقصر', nameEn: 'Luxor' },
      { id: 'c702', nameAr: 'اسنا', nameEn: 'Esna' },
      { id: 'c703', nameAr: 'ارمنت', nameEn: 'Armant' },
      { id: 'c704', nameAr: 'الطود', nameEn: 'Tod' },
      { id: 'c705', nameAr: 'القرنة', nameEn: 'Qurna' },
      { id: 'c706', nameAr: 'الكرنك', nameEn: 'Karnak' },
  ]},
  { id: '8', nameAr: 'البحر الاحمر', nameEn: 'Red Sea', cities: [
      { id: 'c801', nameAr: 'الغردقة', nameEn: 'Hurghada' },
      { id: 'c802', nameAr: 'سفاجا', nameEn: 'Safaga' },
      { id: 'c803', nameAr: 'القصير', nameEn: 'Quseir' },
      { id: 'c804', nameAr: 'مرسى علم', nameEn: 'Marsa Alam' },
      { id: 'c805', nameAr: 'راس غارب', nameEn: 'Ras Gharib' },
      { id: 'c806', nameAr: 'الشلاتين', nameEn: 'Shalateen' },
      { id: 'c807', nameAr: 'حلايب', nameEn: 'Halaib' },
  ]},
  { id: '9', nameAr: 'البحيرة', nameEn: 'Beheira', cities: [
      { id: 'c901', nameAr: 'دمنهور', nameEn: 'Damanhour' },
      { id: 'c902', nameAr: 'كفر الدوار', nameEn: 'Kafr el-Dawar' },
      { id: 'c903', nameAr: 'رشيد', nameEn: 'Rosetta' },
      { id: 'c904', nameAr: 'ادكو', nameEn: 'Edko' },
      { id: 'c905', nameAr: 'ابو حمص', nameEn: 'Abu Hummus' },
      { id: 'c906', nameAr: 'حوش عيسى', nameEn: 'Hosh Essa' },
      { id: 'c907', nameAr: 'الدلنجات', nameEn: 'Delengat' },
      { id: 'c908', nameAr: 'المحمودية', nameEn: 'Mahmoudiyah' },
      { id: 'c909', nameAr: 'ايتاى البارود', nameEn: 'Itay el-Barud' },
      { id: 'c910', nameAr: 'شبراخيت', nameEn: 'Shubrakhit' },
      { id: 'c911', nameAr: 'كوم حمادة', nameEn: 'Kom Hamada' },
      { id: 'c912', nameAr: 'بدر', nameEn: 'Badr' },
      { id: 'c913', nameAr: 'وادى النطرون', nameEn: 'Wadi El Natrun' },
      { id: 'c914', nameAr: 'الرحمانية', nameEn: 'Rahmaniya' },
      { id: 'c915', nameAr: 'ابو المطامير', nameEn: 'Abu al-Matamir' },
  ]},
  { id: '10', nameAr: 'بني سويف', nameEn: 'Beni Suef', cities: [
      { id: 'c1001', nameAr: 'بنى سويف', nameEn: 'Beni Suef' },
      { id: 'c1002', nameAr: 'الواسطى', nameEn: 'Wasta' },
      { id: 'c1003', nameAr: 'ناصر', nameEn: 'Nasser' },
      { id: 'c1004', nameAr: 'اهناسيا', nameEn: 'Ihnasiya' },
      { id: 'c1005', nameAr: 'ببا', nameEn: 'Beba' },
      { id: 'c1006', nameAr: 'سمسطا', nameEn: 'Samasta' },
      { id: 'c1007', nameAr: 'الفشن', nameEn: 'Fashn' },
  ]},
  { id: '11', nameAr: 'بورسعيد', nameEn: 'Port Said', cities: [
      { id: 'c1101', nameAr: 'شرق', nameEn: 'East' },
      { id: 'c1102', nameAr: 'غرب', nameEn: 'West' },
      { id: 'c1103', nameAr: 'الجنوب', nameEn: 'South' },
      { id: 'c1104', nameAr: 'العرب', nameEn: 'Arab' },
      { id: 'c1105', nameAr: 'الزهور', nameEn: 'Zohour' },
      { id: 'c1106', nameAr: 'الضواحى', nameEn: 'Dawahy' },
      { id: 'c1107', nameAr: 'المناخ', nameEn: 'Manakh' },
      { id: 'c1108', nameAr: 'بورفؤاد', nameEn: 'Port Fouad' },
  ]},
  { id: '12', nameAr: 'جنوب سيناء', nameEn: 'South Sinai', cities: [
      { id: 'c1201', nameAr: 'الطور', nameEn: 'El-Tor' },
      { id: 'c1202', nameAr: 'شرم الشيخ', nameEn: 'Sharm El-Sheikh' },
      { id: 'c1203', nameAr: 'دهب', nameEn: 'Dahab' },
      { id: 'c1204', nameAr: 'نويبع', nameEn: 'Nuweiba' },
      { id: 'c1205', nameAr: 'طابا', nameEn: 'Taba' },
      { id: 'c1206', nameAr: 'سانت كاترين', nameEn: 'Saint Catherine' },
      { id: 'c1207', nameAr: 'ابو زنيمة', nameEn: 'Abu Zenima' },
      { id: 'c1208', nameAr: 'ابو رديس', nameEn: 'Abu Rudeis' },
      { id: 'c1209', nameAr: 'راس سدر', nameEn: 'Ras Sedr' },
  ]},
  { id: '13', nameAr: 'الدقهلية', nameEn: 'Dakahlia', cities: [
      { id: 'c1301', nameAr: 'المنصورة', nameEn: 'Mansoura' },
      { id: 'c1302', nameAr: 'طلخا', nameEn: 'Talkha' },
      { id: 'c1303', nameAr: 'ميت غمر', nameEn: 'Mit Ghamr' },
      { id: 'c1304', nameAr: 'السنبلاوين', nameEn: 'Sinbillawain' },
      { id: 'c1305', nameAr: 'بلقاس', nameEn: 'Belqas' },
      { id: 'c1306', nameAr: 'دكرنس', nameEn: 'Dekernes' },
      { id: 'c1307', nameAr: 'اجا', nameEn: 'Aga' },
      { id: 'c1308', nameAr: 'شربين', nameEn: 'Sherbin' },
      { id: 'c1309', nameAr: 'المنزلة', nameEn: 'Manzala' },
      { id: 'c1310', nameAr: 'المطرية', nameEn: 'Matareya' },
      { id: 'c1311', nameAr: 'جمصة', nameEn: 'Gamasa' },
      { id: 'c1312', nameAr: 'نبروة', nameEn: 'Nabaroh' },
  ]},
  { id: '14', nameAr: 'دمياط', nameEn: 'Damietta', cities: [
      { id: 'c1401', nameAr: 'دمياط', nameEn: 'Damietta' },
      { id: 'c1402', nameAr: 'فارسكور', nameEn: 'Faraskur' },
      { id: 'c1403', nameAr: 'الزرقا', nameEn: 'Zarqa' },
      { id: 'c1404', nameAr: 'كفر سعد', nameEn: 'Kafr Saad' },
      { id: 'c1405', nameAr: 'راس البر', nameEn: 'Ras El Bar' },
      { id: 'c1406', nameAr: 'دمياط الجديدة', nameEn: 'New Damietta' },
  ]},
  { id: '15', nameAr: 'سوهاج', nameEn: 'Sohag', cities: [
      { id: 'c1501', nameAr: 'سوهاج', nameEn: 'Sohag' },
      { id: 'c1502', nameAr: 'اخميم', nameEn: 'Akhmim' },
      { id: 'c1503', nameAr: 'جرجا', nameEn: 'Girga' },
      { id: 'c1504', nameAr: 'طما', nameEn: 'Tama' },
      { id: 'c1505', nameAr: 'طهطا', nameEn: 'Tahta' },
      { id: 'c1506', nameAr: 'المراغة', nameEn: 'Maragha' },
      { id: 'c1507', nameAr: 'المنشاة', nameEn: 'Munsha`a' },
      { id: 'c1508', nameAr: 'البلينا', nameEn: 'Balyana' },
      { id: 'c1509', nameAr: 'دار السلام', nameEn: 'Dar El-Salam' },
      { id: 'c1510', nameAr: 'جهينة', nameEn: 'Juhayna' },
      { id: 'c1511', nameAr: 'ساقلتة', nameEn: 'Saqulta' },
  ]},
  { id: '16', nameAr: 'السويس', nameEn: 'Suez', cities: [
      { id: 'c1601', nameAr: 'السويس', nameEn: 'Suez' },
      { id: 'c1602', nameAr: 'الاربعين', nameEn: 'Arbaeen' },
      { id: 'c1603', nameAr: 'عتاقة', nameEn: 'Attaka' },
      { id: 'c1604', nameAr: 'الجناين', nameEn: 'Ganayen' },
      { id: 'c1605', nameAr: 'فيصل', nameEn: 'Faisal' },
  ]},
  { id: '17', nameAr: 'الشرقية', nameEn: 'Sharqia', cities: [
      { id: 'c1701', nameAr: 'الزقازيق', nameEn: 'Zagazig' },
      { id: 'c1702', nameAr: 'العاشر من رمضان', nameEn: '10th of Ramadan' },
      { id: 'c1703', nameAr: 'فاقوس', nameEn: 'Faqous' },
      { id: 'c1704', nameAr: 'بلبيس', nameEn: 'Bilbeis' },
      { id: 'c1705', nameAr: 'منيا القمح', nameEn: 'Minya al-Qamh' },
      { id: 'c1706', nameAr: 'ابو حماد', nameEn: 'Abu Hammad' },
      { id: 'c1707', nameAr: 'الحسينية', nameEn: 'Husseiniya' },
      { id: 'c1708', nameAr: 'ديرب نجم', nameEn: 'Darb Negm' },
      { id: 'c1709', nameAr: 'كفر صقر', nameEn: 'Kafr Saqr' },
      { id: 'c1710', nameAr: 'ابو كبير', nameEn: 'Abu Kebir' },
      { id: 'c1711', nameAr: 'ههيا', nameEn: 'Hehya' },
      { id: 'c1712', nameAr: 'الابراهيمية', nameEn: 'Ibrahimiya' },
      { id: 'c1713', nameAr: 'مشتول السوق', nameEn: 'Mashtoul El-Souk' },
      { id: 'c1714', nameAr: 'صان الحجر', nameEn: 'San el-Hagar' },
      { id: 'c1715', nameAr: 'اولاد صقر', nameEn: 'Awlad Saqr' },
  ]},
  { id: '18', nameAr: 'شمال سيناء', nameEn: 'North Sinai', cities: [
      { id: 'c1801', nameAr: 'العريش', nameEn: 'Arish' },
      { id: 'c1802', nameAr: 'بئر العبد', nameEn: 'Bir al-Abed' },
      { id: 'c1803', nameAr: 'الشيخ زويد', nameEn: 'Sheikh Zuweid' },
      { id: 'c1804', nameAr: 'رفح', nameEn: 'Rafah' },
      { id: 'c1805', nameAr: 'الحسنة', nameEn: 'Hasana' },
      { id: 'c1806', nameAr: 'نخل', nameEn: 'Nakhl' },
  ]},
  { id: '19', nameAr: 'الغربية', nameEn: 'Gharbia', cities: [
      { id: 'c1901', nameAr: 'طنطا', nameEn: 'Tanta' },
      { id: 'c1902', nameAr: 'المحلة الكبرى', nameEn: 'Mahalla al-Kobra' },
      { id: 'c1903', nameAr: 'كفر الزيات', nameEn: 'Kafr el-Zayat' },
      { id: 'c1904', nameAr: 'زفتى', nameEn: 'Zifta' },
      { id: 'c1905', nameAr: 'السنطة', nameEn: 'Santa' },
      { id: 'c1906', nameAr: 'بسيون', nameEn: 'Basyoun' },
      { id: 'c1907', nameAr: 'قطور', nameEn: 'Qutour' },
      { id: 'c1908', nameAr: 'سمنود', nameEn: 'Samanoud' },
  ]},
  { id: '20', nameAr: 'الفيوم', nameEn: 'Faiyum', cities: [
      { id: 'c2001', nameAr: 'الفيوم', nameEn: 'Faiyum' },
      { id: 'c2002', nameAr: 'سنورس', nameEn: 'Sinnuris' },
      { id: 'c2003', nameAr: 'اطسا', nameEn: 'Itsa' },
      { id: 'c2004', nameAr: 'طامية', nameEn: 'Tamiya' },
      { id: 'c2005', nameAr: 'ابشواى', nameEn: 'Ibsheway' },
      { id: 'c2006', nameAr: 'يوسف الصديق', nameEn: 'Yusuf al-Siddiq' },
  ]},
  { id: '21', nameAr: 'قنا', nameEn: 'Qena', cities: [
      { id: 'c2101', nameAr: 'قنا', nameEn: 'Qena' },
      { id: 'c2102', nameAr: 'نجع حمادى', nameEn: 'Nag Hammadi' },
      { id: 'c2103', nameAr: 'ابو تشت', nameEn: 'Abu Tesht' },
      { id: 'c2104', nameAr: 'فرشوط', nameEn: 'Farshout' },
      { id: 'c2105', nameAr: 'دشنا', nameEn: 'Deshna' },
      { id: 'c2106', nameAr: 'الوقف', nameEn: 'Waqf' },
      { id: 'c2107', nameAr: 'قفط', nameEn: 'Qift' },
      { id: 'c2108', nameAr: 'قوص', nameEn: 'Qus' },
      { id: 'c2109', nameAr: 'نقادة', nameEn: 'Naqada' },
  ]},
  { id: '22', nameAr: 'كفر الشيخ', nameEn: 'Kafr el-Sheikh', cities: [
      { id: 'c2201', nameAr: 'كفر الشيخ', nameEn: 'Kafr el-Sheikh' },
      { id: 'c2202', nameAr: 'دسوق', nameEn: 'Desouk' },
      { id: 'c2203', nameAr: 'فوة', nameEn: 'Fuwah' },
      { id: 'c2204', nameAr: 'مطوبس', nameEn: 'Metoubes' },
      { id: 'c2205', nameAr: 'سيدى سالم', nameEn: 'Sidi Salem' },
      { id: 'c2206', nameAr: 'الرياض', nameEn: 'Riyadh' },
      { id: 'c2207', nameAr: 'بيلا', nameEn: 'Bella' },
      { id: 'c2208', nameAr: 'الحامول', nameEn: 'Hamoul' },
      { id: 'c2209', nameAr: 'بلطيم', nameEn: 'Baltim' },
      { id: 'c2210', nameAr: 'قلين', nameEn: 'Qallin' },
  ]},
  { id: '23', nameAr: 'مطروح', nameEn: 'Matrouh', cities: [
      { id: 'c2301', nameAr: 'مرسى مطروح', nameEn: 'Marsa Matrouh' },
      { id: 'c2302', nameAr: 'العلمين', nameEn: 'Alamein' },
      { id: 'c2303', nameAr: 'الحمام', nameEn: 'Hammam' },
      { id: 'c2304', nameAr: 'الضبعة', nameEn: 'Dabaa' },
      { id: 'c2305', nameAr: 'النجيلة', nameEn: 'Negeila' },
      { id: 'c2306', nameAr: 'برانى', nameEn: 'Barrani' },
      { id: 'c2307', nameAr: 'السلوم', nameEn: 'Salloum' },
      { id: 'c2308', nameAr: 'سيوة', nameEn: 'Siwa' },
  ]},
  { id: '24', nameAr: 'المنيا', nameEn: 'Minya', cities: [
      { id: 'c2401', nameAr: 'المنيا', nameEn: 'Minya' },
      { id: 'c2402', nameAr: 'سمالوط', nameEn: 'Samalut' },
      { id: 'c2403', nameAr: 'مطاى', nameEn: 'Matay' },
      { id: 'c2404', nameAr: 'بنى مزار', nameEn: 'Beni Mazar' },
      { id: 'c2405', nameAr: 'مغاغة', nameEn: 'Maghagha' },
      { id: 'c2406', nameAr: 'العدوة', nameEn: 'Adwa' },
      { id: 'c2407', nameAr: 'ابو قرقاص', nameEn: 'Abu Qurqas' },
      { id: 'c2408', nameAr: 'ملوى', nameEn: 'Mallawi' },
      { id: 'c2409', nameAr: 'دير مواس', nameEn: 'Deir Mawas' },
  ]},
  { id: '25', nameAr: 'المنوفية', nameEn: 'Menofia', cities: [
      { id: 'c2501', nameAr: 'شبين الكوم', nameEn: 'Shibin el-Kom' },
      { id: 'c2502', nameAr: 'منوف', nameEn: 'Menouf' },
      { id: 'c2503', nameAr: 'قويسنا', nameEn: 'Quesna' },
      { id: 'c2504', nameAr: 'تلا', nameEn: 'Tala' },
      { id: 'c2505', nameAr: 'بركة السبع', nameEn: 'Birket el-Sab' },
      { id: 'c2506', nameAr: 'الباجور', nameEn: 'Bagour' },
      { id: 'c2507', nameAr: 'الشهداء', nameEn: 'Shohada' },
      { id: 'c2508', nameAr: 'اشمون', nameEn: 'Ashmoun' },
      { id: 'c2509', nameAr: 'السادات', nameEn: 'Sadat' },
  ]},
  { id: '26', nameAr: 'الوادي الجديد', nameEn: 'New Valley', cities: [
      { id: 'c2601', nameAr: 'الخارجة', nameEn: 'Kharga' },
      { id: 'c2602', nameAr: 'الداخلة', nameEn: 'Dakhla' },
      { id: 'c2603', nameAr: 'باريس', nameEn: 'Baris' },
      { id: 'c2604', nameAr: 'الفرافرة', nameEn: 'Farafra' },
      { id: 'c2605', nameAr: 'بلاط', nameEn: 'Balat' },
  ]},
  { id: '27', nameAr: 'القليوبية', nameEn: 'Qalyubia', cities: [
      { id: 'c2701', nameAr: 'بنها', nameEn: 'Banha' },
      { id: 'c2702', nameAr: 'قليوب', nameEn: 'Qalyub' },
      { id: 'c2703', nameAr: 'شبرا الخيمة', nameEn: 'Shubra al-Khaimah' },
      { id: 'c2704', nameAr: 'القناطر الخيرية', nameEn: 'Qanater' },
      { id: 'c2705', nameAr: 'الخانكة', nameEn: 'Khanka' },
      { id: 'c2706', nameAr: 'كفر شكر', nameEn: 'Kafr Shukr' },
      { id: 'c2707', nameAr: 'طوخ', nameEn: 'Toukh' },
      { id: 'c2708', nameAr: 'قها', nameEn: 'Qaha' },
      { id: 'c2709', nameAr: 'الخصوص', nameEn: 'Khosous' },
      { id: 'c2710', nameAr: 'العبور', nameEn: 'Obour' },
  ]},
];

export const workPlanReports: WorkPlanReport[] = [
    {
        id: 'wpr-001',
        startDate: '2025-05-11',
        endDate: '2025-05-11',
        orderNumber: 449,
        executionDate: '2025-05-11',
        atmCode: 'EGBN074',
        atmSerial: 'Alexandria Branch',
        atmAddress: 'فرع الاسكندرية',
        representative: 'mariam@gmail.com',
        status: 'Pending',
        notes: [],
        beforeImages: [],
        afterImages: [],
    },
    {
        id: 'wpr-002',
        startDate: '2025-05-11',
        endDate: '2025-05-11',
        orderNumber: 450,
        executionDate: '2025-05-11',
        atmCode: 'EGBW165',
        atmSerial: 'Kafr Abdo',
        atmAddress: 'كفر عبدو',
        representative: 'mariam@gmail.com',
        status: 'Pending',
        notes: [],
        beforeImages: [],
        afterImages: [],
    },
    {
        id: 'wpr-003',
        startDate: '2025-05-11',
        endDate: '2025-05-11',
        orderNumber: 451,
        executionDate: '2025-05-11',
        atmCode: 'EGBW150',
        atmSerial: 'Stanly Branch',
        atmAddress: 'فرع ستانلي',
        representative: 'mariam@gmail.com',
        status: 'Accepted',
        notes: [],
        beforeImages: [
            "https://picsum.photos/seed/wpr3-before1/400/300",
            "https://picsum.photos/seed/wpr3-before2/400/300",
        ],
        afterImages: [
            "https://picsum.photos/seed/wpr3-after1/400/300",
        ],
    },
    {
        id: 'wpr-004',
        startDate: '2025-05-11',
        endDate: '2025-05-11',
        orderNumber: 452,
        executionDate: '2025-05-11',
        atmCode: 'EGBN100',
        atmSerial: 'Smouha Branch',
        atmAddress: 'فرع سموحة',
        representative: 'mariam@gmail.com',
        status: 'Rejected',
        notes: [],
        beforeImages: [],
        afterImages: [],
    },
    {
        id: 'wpr-005',
        startDate: '2025-05-11',
        endDate: '2025-05-11',
        orderNumber: 453,
        executionDate: '2025-05-11',
        atmCode: 'EGBW144',
        atmSerial: 'Gleem Branch',
        atmAddress: 'فرع جليم',
        representative: 'mariam@gmail.com',
        status: 'Pending',
        notes: [
            { id: 'note-1', text: 'الرجاء التأكد من نظافة الموقع.', date: '2025-05-10', user: 'المراجع' }
        ],
        beforeImages: [],
        afterImages: [],
    }
];
    

    